# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_auto_20170614_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditator',
            name='course_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
